### PR TITLE
Monterey Bay Regional

### PR DESCRIPTION
**Pull request by ky28059**
Cherry picked the relevant commits from `shooter` for easier rebases and merges; this branch will be for tuning shooter constants and behavior in preparation for (and testing) vision and `rtheta`.

Current progress: the turret is able to maintain a locked angle while the robot rotates! Videos on slack.

### CODE REVIEW

**Comment by ky28059** [comment]
For convenience, I'll turn this into the new `subsystems` branch and try to address Liang's concerns on slack directly on here; it's too inconvenient to PR for every subsystem and wait for each request to be merged before changing something else because everything depends on each other.

**Comment by ky28059** [comment]
### From slack:
- [x] fix internals blind zone #25 
- [x] turret blind zone wrapping (jumping across/looping back around)
- [ ] turret blind zone for intake up vs down
- [ ] intake/turret blind zone coordination on retraction
- [x] turret loose tracking when no balls (lazy wrapping)
- [ ] brownout — might occur in pushing competitions, which “fixing” our current system still doesn’t help — we need to prioritize DT in such a pushing match even if flywheel is tryna run #21 
- [x] intake auto stop on two balls
- [x] intake limit switch
- [x] turntable limit switch (does hardware exist?)
- [ ] auto ball pickup/homing (assuming working intake vision) #22 
- [x] structure for when we tune shooter parameters (2d array of flangle + flywheel speed vs distance to hub?)
- [x] turret feed forward?
- [x] turning on + off ring light

**Comment by ky28059** [comment]
For integrated talon limit switches, these are reserved to these options https://www.chiefdelphi.com/t/talon-sr-and-srx-victor-spx-and-limit-switches/342592/11 which all rely on limit switches which plug into the talon data port (none of which I could seem to find in the limit switch drawer). This is probably better for resetting the encoder state anyways.

**Comment by ky28059** [comment]
# Controls Testing / Tuning Todos:

### Turret
- [x] Turntable PIDF
- [x] Hood PID
- [x] Flywheel PIDF
- [x] Turntable angle locking
- [x] Turntable theta feedforward testing / tuning
- [x] Shooter testing, populate interpolation table
- [x] Interpolation testing
- [x] Vision hub tracking
- [x] `rtheta` testing
- [ ] Limit switches?

### Intake
- [x] Driver override testing
- [x] Deploy PID (fix deploy talon encoder wire)
- [x] Limit switch encoder reset

### Internals
- [x] Logic under ideal conditions
- [ ] Logic under unideal conditions (harsh lighting?)
- [ ] Top roller PIDF?

### DT / localization
- [x] Measure `ENCODER_ROTATIONS_TO_METERS`
- [x] Measure `Ka`, `Kv`, and `Ks` with SysId
- [ ] Test path following

### Brownout
- [ ] Test brownout

**Comment by ky28059** [comment]
@e3l For 
> turret blind zone for intake up vs down

does the blind zone actually change when the intake is up? The shooter shoots pretty high doesn't it?

For
> intake/turret blind zone coordination on retraction

what does that mean? Do they collide without coordination if they're both retracting at once?

**Review by eggaskin — DISMISSED** [review]
If it's easier, let's move this to develop to start to condense our many branches.
Things we still need to do after/before then:

- [ ] turret blind zone for intake up vs down
- [ ] intake/turret blind zone coordination on retraction
- [ ] test brownout — might occur in pushing competitions, which “fixing” our current system still doesn’t help — we need to prioritize DT in such a pushing match even if flywheel is tryna run
- [ ] auto ball pickup/homing (assuming working intake vision) for Autonomous
- [ ] turret limit switches
- [x] Intake deploy PID (fix deploy talon encoder wire)
- [x] intake limit switch encoder reset
- [ ] internals tune colors and distance for edge cases
- [ ] internals top roller PIDF? do we really need it
- [ ] DT path following test

**Comment by ky28059** [comment]
@eggaskin have we decided that ball count from entrance sensor is too unreliable and we're just going with
```java
ballCount = (stagingDetected ? 1 : 0) + (storageDetected ? 1 : 0);
```
? If so, I'll remove the auton ball count code because that isn't necessary when ball count is set in periodic from the sensors anyways

**Review by eggaskin — APPROVED** [review]
Code from Monterey Bay Regional, working off of this for SVR.

**Pull request merged**
