### PR TITLE
Brownout fixes

### PR DESCRIPTION
**Pull request by ky28059**
For testing and (hopefully) fixes to brownout jittering behaviors.

### CODE REVIEW

**Comment by ky28059** [comment]
I believe the initial issue with nonsensical limiting was that the sum of the minimum currents for each subsystem added up to above the sustainable current, so the ratio became negative and strange things happened. The minimum currents for each subsystem should be tested, as well as the sustainable current value. Also, Liang brought up that we should run all subsystems at once (without brownout protection) and see if we are even capable of triggering a brownout on low battery.

**Comment by e3l** [comment]
A few things from testing this on the robot:
- there is no more stuttering. that is good.
- we frequently go over 200A. I'm not sure how we should go about actually choosing a max sustainable current.

topic 1:  the current logic uses an ideal ratio of total draw to scale all subsystems. 
- reason 1 why this is bad: it scales all subsystems equally regardless of how much they're drawing. I think the point is to scale down subsystems that aren't using their limit (low ratio) to scale up subsystems that are using their limit (high ratio), e.g. enforce equivalent exchange by using a weighted average weighted by ratios. 
- reason 2 why this is bad: it keeps scaling subsytems up if we're drawing less than total sustainable. so when we're driving slowly the limit just goes higher and higher (past our "total sustainable", which is just silly!)

topic 2: calling setCurrentLimits, getCurrentDrawn, ... every loop is quite expensive

**Comment by ky28059** [comment]
> reason 1 why this is bad: it scales all subsystems equally regardless of how much they're drawing.

The ideal ratio logic should scale subsystems **based** on how much they're drawing. The ratio is determined from total draw and max sustainable current, but the actual scaling for each subsystem multiplies their _draw_ by this ratio. Higher drawing subsystems will be given higher limits than lower drawing subsystems.

**Comment by ky28059** [comment]
> topic 2: calling setCurrentLimits, getCurrentDrawn, ... every loop is quite expensive

Do you think a thread would make this better?

**Comment by eggaskin** [comment]
I think using a ratio based on a subsystem's minimum current (or maybe implement a max? each subsystem is only capable of drawing so much at full throttle, so a max is feasibly, moreso for mechs than dt) and its draw might be more useful. Then like Liang said we can see if a subsystem might need more power in the first place. 
We can also test old brownout, see if that makes more sense limiting-wise.
Have you tested to see if it's still limiting weirdly?

**Comment by eggaskin** [comment]
>     * we frequently go over 200A. I'm not sure how we should go about actually choosing a max sustainable current.

Really, with printed amounts? In my testing max was around 80, but then I guess I wasn't using DT.

**Comment by ky28059** [comment]
Hopefully we can test and merge soon. We could also try and replace recursion with Ethan's limit idea to save processing power
image
but the current algorithm for brownout isn't fundamentally broken (see images on whiteboard), just suffering from some small implementation bugs.

**Review by e3l — COMMENTED** [review]
doesn't seem like the logic has changed, so we really just need to test this to see what aspects we need to fix i guess

**Comment by eggaskin** [comment]
@ky28059 if you have nothing to do during 6th you should test this code, so we can try implementing it asap.

**Comment by ky28059** [comment]
Merged into #32 .

**Pull request closed without merging**
